export const arabicNames = [
    "Ahmed_Amina",
    "Ahmed_Amina",
    "Fatima_Youssef",
    "Ali_Rana",
    "Amina Bilal",
    "Mohammad Layla",
    "Layla Sami",
    "Omar Hana",
    "Zainab Zayd",
    "Hassan Amira",
    "Leila Jad",
    "Abdullah Leen",
    "Maryam Karim",
    "Khalid Dana",
    "Rania Zain",
    "Mustafa Yasmin",
    "Nour Rayan",
    "Youssef Sarah",
    "Sara Nabil",
    "Hussein Rima",
    "Malak Imran",
    "Ahmed Sana",
    "Noor Kareem",
    "Yousef Laila",
    "Hana Tarek",
    "Kareem Nour",
    "Reem Idris",
    "Tariq Leila",
    "Samira Hadi",
    "Mahmoud Ghada",
    "Lina Yara",
    "hamzA badr",
    "Sami Salma",
    "Rana Adam",
    "Anas Aisha",
    "Nada Samir",
    "Adam Inaya",
    "Bilal Mariam",
    "Dalia Nasser",
    "Said Rima"
];
